package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"github.com/guisecreator/um_backend/graphql/model"
)

// UserNew is the resolver for the userNew field.
func (r *mutationResolver) UserNew(ctx context.Context, users []*model.NewUserInput) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: UserNew - userNew"))
}

// UserUpdate is the resolver for the userUpdate field.
func (r *mutationResolver) UserUpdate(ctx context.Context, users []*model.UpdateUserInput) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: UserUpdate - userUpdate"))
}

// UserDelete is the resolver for the userDelete field.
func (r *mutationResolver) UserDelete(ctx context.Context, users []string) (*int, error) {
	panic(fmt.Errorf("not implemented: UserDelete - userDelete"))
}
