FROM golang:latest

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

# RUN go test -v
RUN go build -o server .

EXPOSE 8080

CMD ["./server"]